// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';
part 'response_product_list.g.dart';

@JsonSerializable()
class ResponseProductList {
  ResponseProductList({
    required this.data,
    required this.nextPaging,
  });

  List<ResponseDatum>? data = [];
  int? nextPaging;

  factory ResponseProductList.fromJson(Map<String, dynamic> json) =>
      _$ResponseProductListFromJson(json);
  Map<String, dynamic> toJson() => _$ResponseProductListToJson(this);
}

@JsonSerializable()
class ResponseProduct {
  ResponseProduct({
    required this.data,
  });

  ResponseDatum? data;

  factory ResponseProduct.fromJson(Map<String, dynamic> json) =>
      _$ResponseProductFromJson(json);
  Map<String, dynamic> toJson() => _$ResponseProductToJson(this);
}

@JsonSerializable()
class ResponseDatum {
  ResponseDatum({
    required this.id,
    required this.category,
    required this.title,
    required this.description,
    required this.price,
    required this.texture,
    required this.wash,
    required this.place,
    required this.note,
    required this.story,
    required this.mainImage,
    required this.images,
    required this.variants,
    required this.colors,
    required this.sizes,
  });

  int? id;
  String? category;
  String? title;
  String? description;
  int? price;
  String? texture;
  String? wash;
  String? place;
  String? note;
  String? story;
  String? mainImage;
  List<String>? images = [];
  List<ResponseVariant>? variants = [];
  List<ResponseColor>? colors = [];
  List<ResponseSize>? sizes = [];

  factory ResponseDatum.fromJson(Map<String, dynamic> json) =>
      _$ResponseDatumFromJson(json);
  Map<String, dynamic> toJson() => _$ResponseDatumToJson(this);
}

@JsonSerializable()
class ResponseColor {
  ResponseColor({
    required this.code,
    required this.name,
  });

  String? code;
  String? name;

  factory ResponseColor.fromJson(Map<String, dynamic> json) => _$ResponseColorFromJson(json);
  Map<String, dynamic> toJson() => _$ResponseColorToJson(this);
}

enum ResponseSize { XS, S, M, L, XL, F }

@JsonSerializable()
class ResponseVariant {
  ResponseVariant({
    required this.colorCode,
    required this.size,
    required this.stock,
  });

  String? colorCode;
  ResponseSize? size;
  int? stock;

  factory ResponseVariant.fromJson(Map<String, dynamic> json) =>
      _$ResponseVariantFromJson(json);
  Map<String, dynamic> toJson() => _$ResponseVariantToJson(this);
}
